ASP.NET/ASPNET_MVC/ASPNET_MVC/Models/ErrorViewModel.cs
namespace ASPNET_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Models/Pessoa.cs
namespace ASPNET_MVC.Models
{
    public class Pessoa
    {
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
    }
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Models/Usuario.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
namespace ASPNET_MVC.Models
{
    public class Usuario
    {
        [Required(ErrorMessage = "O nome é obrigatório")]
        public string Nome { get; set; }
        [StringLength(50, MinimumLength = 5, ErrorMessage = "O tamanho minimo é 5 e o maximo é 50")]
        public string Observacoes { get; set; }
        [Range(18, 100, ErrorMessage = "A idade mínima é 18 anos")]
        public int Idade { get; set; }
        [RegularExpression(@"^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$", ErrorMessage = "Email Invalidado")]
        public string Email { get; set; }
        [Required(ErrorMessage = "O Login é obrigatório")]
        [Remote("LogingUnico", "Usuario", ErrorMessage = "Este Login já existe")]
        public string Login { get; set; }
        [StringLength(10, MinimumLength = 5, ErrorMessage = "O tamanho minimo é 5 e o maximo é 10")]
        [Required(ErrorMessage = "A senha é obrigatória")]
        public string Senha { get; set; }
        [StringLength(10, MinimumLength = 5, ErrorMessage = "O tamanho minimo é 5 e o maximo é 10")]
        [Required(ErrorMessage = "A senha é obrigatória")]
        [Compare("Senha", ErrorMessage ="As senhas não coincidem")]
        public string ConfirmarSenha { get; set; }
    }
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Controllers/HomeController.cs
using ASPNET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPNET_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Controllers/Home_1Controller.cs
using ASPNET_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPNET_MVC.Controllers
{
    public class Home_1Controller : Controller
    {
        public IActionResult Index()
        {
            Pessoa pessoa = new Pessoa
            {
                PessoaId = 1, // geralmente a passagem é feita por variáveis que veem do banco de dados
                Nome = "Igor",
                Tipo = "Dev"
            };

            //ViewData["PessoaId"] = pessoa.PessoaId;
            //ViewData["Nome"] = pessoa.Nome;
            //ViewData["Tipo"] = pessoa.Tipo;

            //ViewBag.Id = pessoa.PessoaId;
            //ViewBag.Nome = pessoa.Nome;
            //ViewBag.Tipo = pessoa.Tipo;

            return View(pessoa);
        }

        public IActionResult Contatos()
        {
            return View();
        }

        [HttpPost] // usar o http post, pq se usar o get as informações são passadas na url 
        public IActionResult List(Pessoa pessoa)
        {
            return View(pessoa);
        }
    }
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Controllers/UsuarioController.cs
using ASPNET_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.ObjectModel;

namespace ASPNET_MVC.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Usuario()
        {
            var usuario = new Usuario();
            return View(usuario);
        }
        [HttpPost]
        public IActionResult Usuario(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                return View("Resultado", usuario);
            //return View(Resultado);
            }

            foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
            {
                var errorMessage = error.ErrorMessage;
                System.Diagnostics.Debug.WriteLine(errorMessage);
            }


            return View(usuario);
        }

        public IActionResult Resultado(Usuario usuario) 
        {
            return View(usuario);        
        }

        public IActionResult LogingUnico(string Login) 
        {
            var dbExemple = new Collection<string> 
            {
                "Igor",
                "Jose",
                "Mario",
                "Maria"
            };
            bool result = dbExemple.All(x => x.ToLower() != Login.ToLower());

            return Json(result);
        }

        [HttpPost]
        public IActionResult Search(string searchTerm)
        {
            // Lógica para buscar resultados com base em 'searchTerm'
            var results = new Collection<string>
            {
                "Igor",
                "Jose",
                "Mario",
                "Maria"
            };

            return PartialView("_SearchResultsPartial", results);
        }
    }
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Views/Home_1/Contatos.cshtml
@{
    ViewData["Title"] = "Contatos";
}

<h2>Contatos</h2>

<p>Hello from our View Template!</p>

ASP.NET/ASPNET_MVC/ASPNET_MVC/Views/Home_1/Index.cshtml
@model ASPNET_MVC.Models.Pessoa;

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Hello from our View Template!</p>

<br />
<br />
@*
<p> @ViewData["PessoaId"] </p>
<p> @ViewData["Nome"] </p>
<p> @ViewData["Tipo"] </p>*@

@*<p> @ViewBag.Id </p>
<p> @ViewBag.Nome </p>
<p> @ViewBag.Tipo </p>*@
@*
<p> @Model.PessoaId </p>
<p> @Model.Nome </p>
<p> @Model.Tipo </p>
*@
<p> View Tipada </p>


@using (Html.BeginForm("List", "Home_1", FormMethod.Post))
{
    

@*<form action="Home_1/List" method="post">*@
    <fildset>
        <legend>
            Informações Pessoais
        </legend>
    </fildset> 
    <div>
        @Html.LabelFor(x => x.PessoaId)
    </div>
    <div>
        @*<input type="number" value="@Model.PessoaId" name="PessoaId" />*@
        @Html.EditorFor(x => x.PessoaId)
    </div>

    <div>
        @Html.LabelFor(x => x.Nome)
    </div>
    <div>
        @*<input type="text" value="@Model.Nome" name="Nome" />*@
        @Html.EditorFor(x => x.Nome)
    </div>

    <div>
        @Html.LabelFor(x => x.Tipo)
    </div>
    <div>
        @*<input type="text" value="@Model.Tipo" name="Tipo" />*@
        @Html.EditorFor(x => x.Tipo)
    </div>
    <br />
    <p><input type="submit" value="Enviar" /></p>
@*</form>*@
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Views/Home_1/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ASPNET_MVC.Models.Pessoa;

@{
    <h2> List </h2>
}

<div>
    <b>@Html.LabelFor(x => x.PessoaId)</b>
</div>
<div>
    @Model.PessoaId
</div>


<div>
    <b>@Html.LabelFor(x => x.Nome)</b>
</div>
<div>
    @Model.Nome
</div>



<div>
    <b>@Html.LabelFor(x => x.Tipo)</b>
</div>
<div>
    @Model.Tipo
</div>

@Html.ActionLink("Voltar", "Index", "Home_1")

ASP.NET/ASPNET_MVC/ASPNET_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNET_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPNET_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNET_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <a href="http://google.com" target="_blank">Ir para o google</a>
    <br />
    @Html.ActionLink("Inicial", "Index", "Home_1");
    <br />
    @Html.ActionLink("Contatos", "Contatos", "Home_1");
    <br />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPNET_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src = "~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET/ASPNET_MVC/ASPNET_MVC/Views/Usuario/Resultado.cshtml
@model ASPNET_MVC.Models.Usuario

@{
    ViewData["Title"] = "Resultado";
}

<h2>Resultado</h2>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>
            Usuário cadastrado
        </legend>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.Observacoes)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Observacoes)
        </div>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.Idade)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Idade)
        </div>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.Login)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Login)
        </div>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.Senha)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Senha)
        </div>

        <div class="editor-label">
            @Html.DisplayNameFor(model => model.ConfirmarSenha)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.ConfirmarSenha)
        </div>

        <p>@Html.ActionLink("voltar", "Usuario");</p>
    </fieldset>
}

ASP.NET/ASPNET_MVC/ASPNET_MVC/Views/Usuario/Usuario.cshtml
@model ASPNET_MVC.Models.Usuario
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
@{
    ViewData["Title"] = "Usuario";
}

<h2>Usuário</h2>

<p>Bem vindo, man!</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>
            Dados dos Usuário
        </legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Login)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Login)
            @Html.ValidationMessageFor(model => model.Login)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Observacoes)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Observacoes)
            @Html.ValidationMessageFor(model => model.Observacoes)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Idade)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Idade)
            @Html.ValidationMessageFor(model => model.Idade)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Senha)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(model => model.Senha)
            @Html.ValidationMessageFor(model => model.Senha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ConfirmarSenha)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(model => model.ConfirmarSenha)
            @Html.ValidationMessageFor(model => model.ConfirmarSenha)
        </div>

        <br />

        <p><input type="submit" value="cadastrar"/></p>
    </fieldset>

    


    

}